version: '3.8'
services:
  auth-postgres:
    image: postgres:14.1-alpine
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_USER: $SQL_USERNAME
      POSTGRES_DB: $SQL_DB_NAME
    ports:
      - '5432:5432'
    volumes:
      - ./local-dbs/postgres/:/var/lib/postgresql/data
volumes:
  db:
    driver: local
